services:
  gist-mirror:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opengist-gist-mirror
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"
      DATABASE_URL: "sqlite:////data/app.db"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/data

